### ISSUE TITLE
Undefined variable: descript_ion in /var/www/html/AutoIndex/classes/Item.php on line 205

### ISSUE THREAD

**Issue by mrpong99** [BeitDina/AutoIndex#1]
Undefined variable: descript_ion in /var/www/html/AutoIndex/classes/Item.php on line 205

Apache/2.4.41 (Ubuntu)
MariaDB version 10.3.31
PHP 7.4.3

**Comment by orynider** [comment]
I have Debian 2021 LTS, but I have no time to install a database driver like MariaDB and see no point for AutoIndex. I can add any version of PHP but I loose to much time to stay in Linux at my personal office or at the office of the institute. AutoIndex version can be added to the support template?
I look at the line when I have a spare hour. 10x
BTW, can you show me here online were the line would come:
https://github.com/BeitDina/AutoIndex/blob/master/classes/Item.php

**Comment by orynider** [comment]
For the last version of AutoIndex would not be relevant.
