### ISSUE TITLE
Please update source for >> php v8.1

### ISSUE THREAD

**Issue by agr777** [BeitDina/AutoIndex#2]
Please update source for >> php v8.1

**Comment by silverspr** [comment]
I am having an issue with script not running on php v8.1

**Comment by silverspr** [comment]
@agr777 Hi, seeing that replies have not been forthcoming and if you are still looking for a fix, I found a working fork here:
https://github.com/rubo77/AutoIndex. 
A quick fix which worked for me: replace the index.php and classes/Htaccess.php classes/Url.php files in the old version with the files in the new version (from rubo77).  Good luck.

**Comment by orynider** [comment]
The version rubo77 is making is only taking the folder icons feature but is not compatible with mobile devices. I will take a look Sunday.

**Comment by orynider** [comment]
Seems to be up-to-date ATM with the last version of PHP. Reopen if is not so.

**Comment by TokenRing** [comment]
Sorry orynider - your fork of Justin's wonderful autoindex script does have a lot of visual improvements, but I have to agree with the other posts - it's not working on either PHP 8+ server I tested it on, but rubo77's fork works fine (albeit with fewer graphical whizbangs).
